export const SET_LOGIN_DATA = 'SET_LOGIN_DATA';

export const SET_WALLET_DATA = 'SET_WALLET_DATA';

export const REQUEST_WALLET_DATA = 'REQUEST_WALLET_DAT';

export const RESPONSE_WALLET_SUCCESS = 'RESPONSE_WALLET_SUCCESS';

export const REQUEST_WALLET_FAILURE = 'REQUEST_WALLET_FAILURE';

export const SET_EXPENSES = 'SET_EXPENSES';

export const SET_TOTAL_VALUE = 'SET_TOTAL_VALUE';

export const DELETE_EXPENSE_TABLE = 'DELETE_EXPENSE_TABLE';

export const DECREASE_EXPENSE = 'DECREASE_EXPENSE';

export const EDIT_EXPENSE = 'EDIT_EXPENSE';

export const SET_EDIT = 'SET_EDIT';

export const EDIT_TOTAL_VALUE = 'EDIT_TOTAL_VALUE';
